class CurrentAgg {
    public TYPE: string;
    public MARKET: string;
    public FROMCURRENCY: string;
    public FROMSYMBOL: string;
    public TOCURRENCY: string;
    public TOSYMBOL: string;
    public FLAGS: string;
    public PRICE: number;
    public BID: number;
    public OFFER: number;
    public LASTUPDATE: number;
    public AVG: number;
    public LASTVOLUME: number;
    public LASTVOLUMETO: number;
    public LASTTRADEID: number;
    public VOLUMEHOUR: number;
    public VOLUMEHOURTO: number;
    public VOLUME24HOUR: number;
    public VOLUME24HOURTO: number;
    public OPENHOUR: number;
    public HIGHHOUR: number;
    public LOWHOUR: number;
    public OPEN24HOUR: number;
    public HIGH24HOUR: number;
    public LOW24HOUR: number;
    public LASTMARKET: string;
}